language:
  - cpp

install:
  - sudo pip install cpp-coveralls

script:
  - cd test
  - mkdir build
  - cd build
  - cmake .. 
  - make
  - ctest
after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"

notifications:
  email: false
